---
feature: plan-artifact-lifecycle
issue: 117
created: 2026-03-02
architecture-spec: plan/architect-plan-artifact-lifecycle.md
feature-context: plan/feature-context-plan-artifact-lifecycle.md
---

# Tasks: Plan Artifact Lifecycle Policy (Issue #117)

Six tasks implement the plan artifact lifecycle policy from
[plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md).
All changes are documentation and workflow policy only. No Python scripts are created or modified.

## Dependency Graph

```text
T1 (policy doc) ──────────────────────────────────────┐
                                                       │
T6 (TASK_FILE_FORMAT.md schema) ── no deps            │
                                                       ▼
                 T2 (local-workflow.md) ◄── T1
                 T3 (start-task SKILL.md) ◄── T1
                 T5 (context-refinement.md) ◄── T1
                                                 │
                                                 ▼
                              T4 (complete-implementation SKILL.md) ◄── T5
```

Parallel execution opportunities:

- T1 and T6 can start immediately (no dependencies)
- T2, T3, and T5 can start in parallel after T1 completes
- T4 must wait for T5 to complete

---

## Context Manifest

_Generated by context-gathering agent on 2026-03-02_

### How This Feature Fits Into the SAM Workflow

The SAM (Stateless Agent Methodology) workflow produces plan artifacts during `/add-new-feature` and then implements them in `/implement-feature`. The six tasks in this plan introduce a lifecycle policy that addresses a structural gap: once created, plan artifacts were never updated, leaving them as write-once snapshots that diverge silently from what was actually built.

The workflow that this feature policy governs flows in three phases. During Phase 1 (`/add-new-feature`), the `feature-researcher` agent produces `plan/feature-context-{slug}.md`, the `codebase-analyzer` agent produces `plan/codebase/{FOCUS}.md` (optional), the `python-cli-design-spec` agent produces `plan/architect-{slug}.md`, and the `swarm-task-planner` agent produces the task file `plan/tasks-{N}-{slug}.md`. The `context-gathering` agent then populates the `## Context Manifest` section inside the task file. All of these artifacts are written once and never revisited.

During Phase 2 (`/implement-feature`), the orchestrator queries `implementation_manager.py` for ready tasks, then delegates each to its assigned agent via the `/start-task` skill. The `/start-task` skill marks the task `in-progress`, writes `.claude/context/active-task-{session_id}.json` for hook consumption, and instructs the agent to implement against the task's acceptance criteria. A `PostToolUse` hook fires on every Write/Edit/Bash call and updates `LastActivity` in the task file. When the sub-agent finishes, a `SubagentStop` hook sets the task to `complete` and writes the `completed` timestamp.

During Phase 3 (`/complete-implementation`), six quality gate phases run sequentially. Phase 6 launches the `context-refinement` agent, which currently updates only the task file's `## Context Manifest` section with a `### Discovered During Implementation` subsection. This is the only point in the workflow where any plan artifact receives any update. The feature-context and architect spec files receive no updates whatsoever — they remain as they were created.

This feature adds divergence recording at the `/start-task` level (Step 5a) and expands the `context-refinement` agent's scope at `/complete-implementation` Phase 6 (new Steps 5-8) so that plan artifacts receive annotations describing what actually changed during implementation. A canonical policy document (`.claude/docs/plan-artifact-lifecycle.md`) is created to hold the taxonomy and rules, and `TASK_FILE_FORMAT.md` is extended with a `divergence-notes` counter field.

### What Each Task Produces and Why the Order Matters

T1 creates `.claude/docs/plan-artifact-lifecycle.md` — the canonical policy document that T2, T3, T4, and T5 all reference via relative links. T1 must complete before T2, T3, or T5 can write their references, because those tasks verify that the link target exists before writing. T6 runs in parallel with T1 because it writes to `TASK_FILE_FORMAT.md` only, with no dependency on the policy document.

T2, T3, and T5 run in parallel after T1 completes. They write to three distinct files with no overlap: T2 writes to `.claude/rules/local-workflow.md`, T3 writes to `.claude/skills/start-task/SKILL.md`, and T5 writes to `plugins/python3-development/agents/context-refinement.md`.

T4 runs last because it updates `.claude/skills/complete-implementation/SKILL.md` to describe the expanded Phase 6 behavior, and that description must accurately reference what T5 added to the `context-refinement` agent. T4 reads `context-refinement.md` to confirm the `DIVERGENCE_REQUIRING_REVIEW` block name before writing its reference.

### Critical File: `.claude/docs/plan-artifact-lifecycle.md` (T1)

This file does not yet exist. The implementer creates it. Its full required content is specified in `plan/architect-plan-artifact-lifecycle.md`, sections "Policy Document: `.claude/docs/plan-artifact-lifecycle.md`", "Artifact Classification Taxonomy", "Resolved Design Questions Q1-Q5", "Divergence Recording During Task Execution", "Extended Context-Refinement Agent", and "Backward Compatibility".

The file must contain exactly nine sections in this order: Purpose and Scope, Artifact Classification, Rules for Human-Decision Artifacts, Rules for Generated Artifacts, Divergence Detection, Divergence Classification, Divergence Recording, Divergence Reporting, Backward Compatibility.

Cross-references in this file point to: `.claude/rules/local-workflow.md`, `.claude/docs/TASK_FILE_FORMAT.md`, `.claude/skills/start-task/SKILL.md`, and `plugins/python3-development/agents/context-refinement.md`. All four paths must be verified with the `Read` tool before use. The relative paths from `.claude/docs/plan-artifact-lifecycle.md` to these files are `./rules/local-workflow.md`, `./TASK_FILE_FORMAT.md`, `./skills/start-task/SKILL.md`, and `./../plugins/python3-development/agents/context-refinement.md`. Verify existence before writing.

The divergence note format block in this document defines the format agents use in task files:

```text
## Divergence Notes

### DN-1: {Brief title}

- **Plan artifact**: plan/architect-{slug}.md, section "{section name}"
- **Plan claim**: "{quoted text from plan artifact}"
- **Actual implementation**: "{what was actually done and why}"
- **Classification**: design-refinement | intent-divergence
- **Recorded**: {ISO timestamp}
```

The divergence threshold table (from the Q1 resolution in the architecture spec) classifies five change types: implementation detail differs from architect spec (design-refinement, auto-record), approach differs but achieves same goal from backlog item (design-refinement, auto-record and annotate), scope expanded or reduced beyond backlog item (intent-divergence, flag for review), goal redefined or abandoned (intent-divergence), constraint from grooming output violated (intent-divergence).

### Critical File: `.claude/rules/local-workflow.md` (T2)

This file exists at `/home/user/claude_skills/.claude/rules/local-workflow.md`. Read it before editing.

Three locations in this file need changes:

1. The `### Artifacts Produced` table (line ~32) currently has three columns: Artifact, Path, Created By. A fourth column `Artifact Type` must be added. The four rows get values: Feature context → `Generated`, Codebase analysis → `Generated (snapshot)`, Architecture spec → `Generated`, Task plan → `Generated`.

2. A new `## Plan Artifact Lifecycle` section must be inserted between Phase 1 and Phase 2 content (or after the Artifacts Produced table and before Agent Delegation Sequence — read the file to determine the natural insertion point). This section contains: a one-paragraph summary of the two artifact categories, a link to `.claude/docs/plan-artifact-lifecycle.md`, a two-column table (Artifact Type | Mutability Rule), and a note that divergence detection runs in Phase 6.

3. The Phase 3 Phase Sequence table (line ~221, currently reads `Phase 6: context-refinement -> Update task file Context Manifest`) must update to read `Phase 6: context-refinement -> Update task file Context Manifest + plan artifact freshness check`.

4. The Data Flow Diagram's `/complete-implementation` block (line ~342, currently `└─ context-refinement ──> updated Context Manifest`) must have two new lines appended beneath it:

```text
                                ──> plan artifact annotations (if divergence found)
                                ──> DIVERGENCE_REQUIRING_REVIEW (if intent divergence)
```

Relative path from this file to the policy doc: The file is at `.claude/rules/local-workflow.md` and the policy doc is at `.claude/docs/plan-artifact-lifecycle.md`. Correct relative path: `./../docs/plan-artifact-lifecycle.md`.

### Critical File: `.claude/skills/start-task/SKILL.md` (T3)

This file exists at `/home/user/claude_skills/.claude/skills/start-task/SKILL.md`. Read it before editing.

The current step sequence at the bottom of the file is:

- Step 1: Read the task file and the linked architecture spec
- Step 2: Select the task (with substep 2a for skill loading)
- Step 3: Update task status
- Step 4: Write the active-task context file (the bash command writing to `.claude/context/active-task-${CLAUDE_SESSION_ID}.json`)
- Step 5: Implement against the task acceptance criteria and run its verification steps

The new step 5a must be inserted between step 4 (write context file) and step 5 (implement). After insertion, the original step 5 must be renumbered to step 6. The architecture spec describes this new step as step "5a" in the spec text but the task file says to number it sequentially (the original step 5 becomes step 6). The task description says "insert a new step between step 4 and step 5" and "Renumber the original step 5 to step 6."

The inserted step content is exactly as written in task T3's Requirements section. It includes a nested `## Divergence Notes` code fence example with language specifier `markdown`, and a link to the policy document. The relative path from `.claude/skills/start-task/SKILL.md` to `.claude/docs/plan-artifact-lifecycle.md` is `./../docs/plan-artifact-lifecycle.md` — confirmed by directory counting: the file is one level inside `.claude/skills/start-task/`, so two levels up (`./../..`) reaches repo root, then `.claude/docs/plan-artifact-lifecycle.md`. However, since both files are under `.claude/`, the correct relative path is `./../docs/plan-artifact-lifecycle.md` (up one level from `start-task/` to `skills/`, then up one more to `.claude/`, then down into `docs/`). Verify by reading both files' locations before writing.

The nested code fence in the step content requires careful backtick counting. The outer code fence in the task file uses triple backticks with `markdown` language specifier. The inner example uses triple backticks. In the SKILL.md file itself, the outer fence that wraps the entire step example should use the minimum needed to not conflict with the inner fence's triple backticks — use four backticks on the outer if needed. Follow the existing SKILL.md formatting conventions for nested fences.

### Critical File: `.claude/skills/complete-implementation/SKILL.md` (T4)

This file exists at `/home/user/claude_skills/.claude/skills/complete-implementation/SKILL.md`. Read it before editing.

The current `## Phase 6: Context Refinement` section text is exactly:

```text
Launch `context-refinement` to update the task file Context Manifest with discoveries from implementation (only if needed).
```

This single sentence is the entire Phase 6 content. It must be replaced with a multi-sentence description that references the plan artifact freshness check, mentions `design-refinement or intent-divergence` classification, and includes a relative link to `.claude/docs/plan-artifact-lifecycle.md`.

After the `## Phase 6` section and before `## Recursive Follow-up Handling`, a new `## Post-Phase-6: Surface Divergence Findings` section must be inserted. This section contains a `text` code fence showing the format for surfacing divergence findings to the human. The new section includes the literal string `DIVERGENCE_REQUIRING_REVIEW` as the signal to check for.

Relative path from `.claude/skills/complete-implementation/SKILL.md` to policy doc: `./../docs/plan-artifact-lifecycle.md` (same logic as start-task: up one level from `complete-implementation/` to `skills/`, then up one level to `.claude/`, then down to `docs/`).

The T4 task specifies: the nested `text` code fence inside the new section must use `text` as the language specifier. Watch for nested backtick count. The outer block uses ` ```markdown ` and the inner uses ` ```text `.

### Critical File: `plugins/python3-development/agents/context-refinement.md` (T5)

This file exists at `/home/user/claude_skills/plugins/python3-development/agents/context-refinement.md`. Read it before editing.

The current file has exactly four process steps under `## Process`: Step 1 (Read Task File and Architecture Spec), Step 2 (Analyze Implementation for Discoveries), Step 3 (Decision Point), Step 4 (Update Format). There is no Step 5 currently — confirmed by the T5 CoVe checks section. The current file structure has these sections: `## YOUR MISSION`, `## Context About Your Invocation`, `## Process` (with Steps 1-4), `## What Qualifies as Worth Updating`, `## Self-Check Before Finalizing`, `## Examples`, `## Output Format (DONE/BLOCKED Signaling)` (with subsections), `## Remember`.

Four changes are needed:

1. `## YOUR MISSION` text changes from "Only update the context manifest if changes are needed." to "Update the context manifest if changes are needed. Then perform a plan artifact freshness check: compare the feature-context and architect spec against the actual implementation to detect and classify divergences as design-refinement or intent-divergence."

2. After `## Context About Your Invocation`, insert a policy reference paragraph: "For artifact classification rules, divergence thresholds, and annotation formats, see [.claude/docs/plan-artifact-lifecycle.md](./../../.claude/docs/plan-artifact-lifecycle.md)." The relative path from `plugins/python3-development/agents/context-refinement.md` to `.claude/docs/plan-artifact-lifecycle.md` is `./../../.claude/docs/plan-artifact-lifecycle.md` — confirmed by the T5 CoVe section: the agent file is at `plugins/python3-development/agents/` (three levels deep), and `.claude/docs/` is one level deep, so the relative path goes up two levels from `agents/` to `python3-development/` to `plugins/`, then needs one more up to repo root to find `.claude/`. Correct path: `./../../.claude/docs/plan-artifact-lifecycle.md`. Verify before writing.

3. After Step 4 in the `## Process` section, append four new steps: Step 5 (Locate Plan Artifacts and Intent Source), Step 6 (Collect Divergence Evidence), Step 7 (Classify Divergences), Step 8 (Annotate Plan Artifacts). Each step is a `### Step N: Title` heading. The full step content for each is specified in task T5's Requirements section. Step 8 contains a nested `## Post-Implementation Annotations` markdown block with `### Design Refinements` and `### Intent Divergences Requiring Review` subsections. The annotation rule is APPEND ONLY — never modify original plan artifact content.

4. In `## Output Format (DONE/BLOCKED Signaling)`, two changes: (a) the "On Success - Context Updated" block's SUMMARY line template changes to include "Plan artifact freshness check found [M] design refinements, [K] intent divergences", and its ARTIFACTS block gains two optional entries for annotated files. (b) A new "On Success - Intent Divergence Found" subsection is added after "On Success - Context Updated", containing the `DIVERGENCE_REQUIRING_REVIEW` output block format.

The `DIVERGENCE_REQUIRING_REVIEW` output block format as it will appear in the agent's output:

```text
DIVERGENCE_REQUIRING_REVIEW:
  1. [Title]: [Brief description]
     - Human intent: [quoted]
     - Actual: [description]
     - Task: [task file path]
```

### Critical File: `.claude/docs/TASK_FILE_FORMAT.md` (T6)

This file exists at `/home/user/claude_skills/.claude/docs/TASK_FILE_FORMAT.md`. Read it before editing.

Three locations need changes:

1. The Optional Fields table (lines ~139-153) currently ends with the `analysis-method` row. A new row must be appended after it:

   `| divergence-notes | integer | Count of divergence notes recorded during implementation | 2 |`

2. The JSON Schema `properties` block (lines ~268-372) currently ends with the `analysis-method` property and then the closing `}` of properties. After `analysis-method` and before the closing `}`, a new property must be added:

```json
"divergence-notes": {
  "type": "integer",
  "minimum": 0,
  "default": 0,
  "description": "Count of divergence notes recorded during implementation"
}
```

The preceding `analysis-method` property (ending with `}` before the close of `properties`) currently has NO trailing comma (the `analysis-method` property is the last one). The new property must be preceded by a comma added to the `analysis-method` closing brace. Read the actual file JSON carefully to confirm the exact insertion point and whether a comma is needed on the preceding property.

3. The template file contents block in `## Template File` section must gain a commented line for `divergence-notes` after the `# analysis-method` comment line:

```text
# divergence-notes: 0   # OPTIONAL: integer count of ## Divergence Notes sections in body
```

Backward-compatibility verification: run `uv run plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py validate . plugin-linter` — must exit 0. The `implementation_manager.py` parser ignores unknown YAML fields, so the new optional field does not affect existing task files.

### Repository Conventions That Affect All Tasks

All modified files must pass the linter. The linter command is:

```bash
uv run prek run --files <modified-file>
```

Key linting rules enforced in this repository:

- MD031: All fenced code blocks must be surrounded by blank lines (before the opening fence and after the closing fence)
- All code fences must have a language specifier (`markdown`, `text`, `json`, `bash`, `yaml`, `python`)
- MD links must use `./` relative paths (never absolute paths, never bare backtick paths)
- Nested code blocks: outer fence uses 4+ backticks, inner uses 3 backticks (applies when showing markdown inside markdown)

The `.pre-commit-config.yaml` is run via `prek`, not `pre-commit`. Use `uv run prek run --files <file>` — not `pre-commit run`.

### Relative Path Reference Table

All six tasks write relative links to `.claude/docs/plan-artifact-lifecycle.md`. The correct relative paths from each file's location:

| File | Relative path to policy doc |
|---|---|
| `.claude/docs/plan-artifact-lifecycle.md` | N/A (the file itself) |
| `.claude/rules/local-workflow.md` | `./../docs/plan-artifact-lifecycle.md` |
| `.claude/skills/start-task/SKILL.md` | `./../docs/plan-artifact-lifecycle.md` |
| `.claude/skills/complete-implementation/SKILL.md` | `./../docs/plan-artifact-lifecycle.md` |
| `plugins/python3-development/agents/context-refinement.md` | `./../../.claude/docs/plan-artifact-lifecycle.md` |

Verify each path with `Read` before writing. The policy doc (T1 output) does not exist yet at time of T2, T3, T5 execution — those tasks must be run after T1 completes, so the file will exist by the time they run.

### Pre-Existing Schema Divergences (Not in Scope)

The codebase analysis at `plan/codebase/plan-artifact-lifecycle.md` documents five divergences between `TASK_FILE_FORMAT.md` and actual task files in the repository:

1. `accuracy-risk` field is used in task files but not in the schema (ignored by parser)
2. `reason` and `handoff` fields appear in YAML frontmatter of newer task files but are not in the schema
3. `@` prefix on agent names in older task files conflicts with the schema example format
4. `issue-classification`, `scenario-target`, `analysis-method` fields existed in the schema before this feature added them (now documented)
5. Feature-context files accurately describe pre-implementation state; after implementation they diverge (expected, this is the problem this feature addresses)

These are not in scope for this implementation. Do not modify the schema for `accuracy-risk`, `reason`, `handoff`, or `@`-prefixed agent names in this set of tasks.

### Artifacts the `context-refinement` Agent (T5) Will Read During Freshness Checks

After T5 is deployed, the expanded `context-refinement` agent will locate plan artifacts by reading paths from the task file header and architecture spec header. These headers are the YAML frontmatter fields `architecture-spec` and `feature-context` in task files (e.g., this task file's frontmatter contains `architecture-spec: plan/architect-plan-artifact-lifecycle.md` and `feature-context: plan/feature-context-plan-artifact-lifecycle.md`). The agent will also read the `Intent Source` field from the plan artifact headers — a new field that new artifacts will have but existing ones lack. When `Intent Source` is absent, the agent defaults all divergences to `design-refinement` (safe default, no human review triggered).

### Technical Reference Details

#### Files to Create

| File | Created by | Task |
|---|---|---|
| `/home/user/claude_skills/.claude/docs/plan-artifact-lifecycle.md` | T1 agent | T1 |

#### Files to Modify

| File | Absolute path | Task | Changes |
|---|---|---|---|
| `local-workflow.md` | `/home/user/claude_skills/.claude/rules/local-workflow.md` | T2 | Artifacts table (add Artifact Type column), new Plan Artifact Lifecycle section, Phase 6 description update, Data Flow Diagram update |
| `start-task/SKILL.md` | `/home/user/claude_skills/.claude/skills/start-task/SKILL.md` | T3 | New Step 5a between steps 4 and 5; original step 5 becomes step 6 |
| `complete-implementation/SKILL.md` | `/home/user/claude_skills/.claude/skills/complete-implementation/SKILL.md` | T4 | Phase 6 text replacement; new Post-Phase-6 section |
| `context-refinement.md` | `/home/user/claude_skills/plugins/python3-development/agents/context-refinement.md` | T5 | Mission update, policy reference, Steps 5-8, updated output format |
| `TASK_FILE_FORMAT.md` | `/home/user/claude_skills/.claude/docs/TASK_FILE_FORMAT.md` | T6 | Optional Fields table row, JSON schema property, template comment |

#### Files Explicitly Unchanged

`plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py` — no script changes. The parser already ignores unknown YAML fields, so `divergence-notes` requires no parser update.

`plugins/python3-development/skills/implementation-manager/scripts/task_status_hook.py` — no hook changes.

All generator agents (`feature-researcher.md`, `swarm-task-planner.md`, `python-cli-design-spec.md`) — not modified. Lifecycle metadata (`Artifact Type`, `Intent Source`) is described as a new header format for future artifacts but requires no change to the generators in this implementation (generators produce artifacts according to templates, and those templates are described in the policy doc; the generators themselves are not changed).

`plugins/python3-development/agents/doc-drift-auditor.md` — not modified. Its scope is documentation vs code; the new freshness check is plan artifact vs implementation. These are complementary, not overlapping.

`plugins/python3-development/agents/feature-verifier.md` — not modified. It reads plan artifacts as ground truth. Post-implementation annotations are appended sections that the verifier can distinguish from original content.

#### SYNC CHECKPOINT: Post-Completion Quality Gates

After all six tasks complete, verify:

1. `.claude/docs/plan-artifact-lifecycle.md` exists with all nine required sections
2. `Grep(pattern="freshness check", path=".claude/skills/complete-implementation/SKILL.md")` returns a match
3. `Grep(pattern="DIVERGENCE_REQUIRING_REVIEW", path="plugins/python3-development/agents/context-refinement.md")` returns a match
4. `Grep(pattern="divergence-notes", path=".claude/docs/TASK_FILE_FORMAT.md")` returns matches in table, schema, and template
5. `Grep(pattern="plan-artifact-lifecycle.md", path=".claude/rules/local-workflow.md")` returns a match
6. All linter runs passed (each task ran `uv run prek run --files <modified-file>` with exit 0)
7. `uv run plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py validate . plugin-linter` exits 0

---

## Task T1: Create plan-artifact-lifecycle.md Policy Document

```yaml
---
task: T1
title: Create plan-artifact-lifecycle.md policy document
status: complete
started: 2026-03-02T00:00:00Z
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: []
priority: 1
complexity: medium
accuracy-risk: low
parallelize-with: [T6]
reason: T1 and T6 write to different files with no overlap
handoff: >
  Report: file created at .claude/docs/plan-artifact-lifecycle.md,
  confirm all 9 required sections present, confirm all cross-reference
  paths resolve to existing files.
---
```

## Context

This task was planned as a standalone creation task. The policy document is the canonical
reference for the artifact lifecycle policy. All other tasks in this plan reference it.

The architecture spec defines the required content at
[plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
sections "Policy Document" and "Artifact Classification Taxonomy".

## Objective

Create `.claude/docs/plan-artifact-lifecycle.md` containing the canonical plan artifact
lifecycle policy with all nine required sections as specified in the architecture spec.

## Required Inputs

- [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md) —
  primary source: sections "Policy Document: Required Sections",
  "Artifact Classification Taxonomy", "Resolved Design Questions", "Divergence Recording",
  "Extended Context-Refinement Agent", "Backward Compatibility"
- [.claude/docs/TASK_FILE_FORMAT.md](../.claude/docs/TASK_FILE_FORMAT.md) — to reference
  correctly in cross-references section
- [.claude/skills/start-task/SKILL.md](../.claude/skills/start-task/SKILL.md) — to confirm
  correct path for cross-reference
- [plugins/python3-development/agents/context-refinement.md](../plugins/python3-development/agents/context-refinement.md)
  — to confirm correct path for cross-reference

## Requirements

1. Create the file at `/home/user/claude_skills/.claude/docs/plan-artifact-lifecycle.md`
2. Include all nine required sections in this order:
   1. Purpose and Scope
   2. Artifact Classification (two-category taxonomy with tables)
   3. Rules for Human-Decision Artifacts (3 rules)
   4. Rules for Generated Artifacts (4 rules)
   5. Divergence Detection (when and how divergence is detected)
   6. Divergence Classification (the threshold table from Q1 resolution)
   7. Divergence Recording (divergence note format for `/start-task`)
   8. Divergence Reporting (how findings surface at `/complete-implementation`)
   9. Backward Compatibility (forward-only policy, existing artifacts unaffected)
3. Include the human-decision artifacts table (backlog items, grooming output,
   fact-check results, RT-ICA assessments, interview transcripts, human design decisions)
4. Include the generated artifacts table (feature context, codebase analysis, architecture
   spec, task plan, Context Manifest) with Created By and Updated By columns
5. Include the divergence threshold classification table (5 rows: implementation detail
   differs, approach differs but same goal, scope expanded/reduced, goal redefined/abandoned,
   constraint violated)
6. Include the divergence note format block (DN-N, plan artifact, plan claim, actual
   implementation, classification, recorded timestamp)
7. Include the DIVERGENCE_REQUIRING_REVIEW output block format as it will appear in
   context-refinement output
8. Include the Annotation vs Rewrite Distinction section
9. Use relative markdown links starting with `./` for all cross-references
10. Add language specifiers to all code fences
11. Surround all fenced code blocks with blank lines

## Constraints

- Do not create a Python script or tool — this is documentation only
- Do not modify any existing file in this task
- Do not add content not derived from the architecture spec
- All cross-reference paths must point to files that exist in the repository
- Do not use `@` or `/` skill reference prefixes in prose — use markdown links to the
  actual files

## Expected Outputs

- File created: `/home/user/claude_skills/.claude/docs/plan-artifact-lifecycle.md`

## Acceptance Criteria

1. File exists at `/home/user/claude_skills/.claude/docs/plan-artifact-lifecycle.md`
2. All nine required sections are present (readable with `Read` tool and confirmed by
   section heading search)
3. The human-decision artifacts table contains all six artifact types listed in the spec
4. The generated artifacts table contains all five artifact types with Created By and
   Updated By columns
5. The divergence threshold table contains all five change-type rows
6. The divergence note format block shows `DN-N`, `plan artifact`, `plan claim`,
   `actual implementation`, `classification`, and `recorded` fields
7. All relative markdown links use `./` prefix and point to files that exist (verify
   each path with `Read` tool before writing)
8. All code fences have language specifiers
9. `uv run prek run --files .claude/docs/plan-artifact-lifecycle.md` exits 0

## Verification Steps

1. Read the file and confirm all nine section headings are present
2. Search the file for each required table: `Grep(pattern="Human-Decision",
   path=".claude/docs/plan-artifact-lifecycle.md")` and
   `Grep(pattern="Generated Artifacts", path=".claude/docs/plan-artifact-lifecycle.md")`
3. Confirm the divergence threshold table rows:
   `Grep(pattern="intent-divergence", path=".claude/docs/plan-artifact-lifecycle.md",
   output_mode="count")` — expect at least 3 matches
4. Verify all referenced file paths exist by running `Read` on each one before including
   the link
5. Run linter: `uv run prek run --files .claude/docs/plan-artifact-lifecycle.md`

## Handoff

Return:

- Confirmation that file was created with all 9 sections
- List of all cross-references included and their verified file paths
- Output of linter run (pass or failure with errors)
- Any content from the architecture spec that was ambiguous or required interpretation

---

## Task T2: Update local-workflow.md — Add Artifact Lifecycle Section

```yaml
---
task: T2
title: Update local-workflow.md — add artifact lifecycle section
status: complete
started: 2026-03-02T00:00:00Z
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: [T1]
priority: 2
complexity: medium
accuracy-risk: low
parallelize-with: [T3, T5]
reason: T2, T3, T5 write to different files with no overlap
handoff: >
  Report: sections added/modified in local-workflow.md, line ranges of each
  change, linter pass/fail.
---
```

## Context

This task was planned as a standalone update. `local-workflow.md` is the SAM workflow
documentation that human operators and orchestrators read to understand the full pipeline.
It needs a new section describing the plan artifact lifecycle policy and updated tables and
diagrams to reflect the expanded Phase 6 behavior.

T1 must complete first because this task references
`.claude/docs/plan-artifact-lifecycle.md` in a new cross-reference link.

Architecture spec source: [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
sections "Modifications to local-workflow.md".

## Objective

Add a Plan Artifact Lifecycle section to `.claude/rules/local-workflow.md`, update the
Phase 1 Artifacts Produced table to include an Artifact Type column, update the Phase 3
quality gate Phase 6 description, and update the Data Flow Diagram's
`/complete-implementation` block.

## Required Inputs

- [.claude/rules/local-workflow.md](../.claude/rules/local-workflow.md) — file to modify;
  read before editing
- [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md) —
  sections "Modifications to local-workflow.md"
- `.claude/docs/plan-artifact-lifecycle.md` — must exist (T1 output); used as link target

## Requirements

### Artifacts Produced table update

1. Read the existing "Artifacts Produced" table in the Phase 1 section (currently 4 columns:
   Artifact, Path, Created By)
2. Add a fourth column `Artifact Type` to the table header
3. Add values for each row: Feature context → `Generated`, Codebase analysis →
   `Generated (snapshot)`, Architecture spec → `Generated`, Task plan → `Generated`

### New Plan Artifact Lifecycle section

4. Insert a new section titled `## Plan Artifact Lifecycle` after the "Artifacts Produced"
   table and before the "Agent Delegation Sequence" subsection (or as a top-level section
   between Phase 1 and Phase 2 — place it where it reads most naturally for a human
   scanning the document)
5. The new section must include:
   - A one-paragraph summary of the two artifact categories (human-decision and generated)
   - A reference link to `.claude/docs/plan-artifact-lifecycle.md` for full taxonomy
   - A two-column table: Artifact Type | Mutability Rule (human-decision: immutable,
     generated: mutable but intent-bound)
   - A note that divergence detection runs in Phase 6 of `/complete-implementation`

### Phase 3 quality gate Phase 6 description update

6. Find the Phase 6 line in the Phase Sequence table or list under Phase 3
   (`/complete-implementation`). The current text is:
   `Phase 6: context-refinement -> Context Manifest update`
   (or equivalent wording — read the file to find the exact current text)
7. Update the Phase 6 description to:
   `Phase 6: context-refinement -> Update task file Context Manifest + plan artifact freshness check`

### Data Flow Diagram update

8. In the `/complete-implementation` block of the Data Flow Diagram, find the
   `context-refinement` line. The current text ends with `updated Context Manifest`.
   Append two new lines beneath it:
   ```text
   ──> plan artifact annotations (if divergence found)
   ──> DIVERGENCE_REQUIRING_REVIEW (if intent divergence)
   ```
9. Preserve all existing diagram content — only append, do not reformat

## Constraints

- Read the full file before editing to understand existing structure and exact wording
- Do not rewrite sections not listed in Requirements
- Do not change the diagram arrows or formatting style for existing lines
- Use `./` relative paths in all new markdown links
- All new code fences must have language specifiers
- All new fenced code blocks must be surrounded by blank lines

## Expected Outputs

- File modified: `/home/user/claude_skills/.claude/rules/local-workflow.md`

## Acceptance Criteria

1. The Artifacts Produced table has an `Artifact Type` column with values for all four rows
2. A `## Plan Artifact Lifecycle` section exists in the file
3. The new section contains a link to `.claude/docs/plan-artifact-lifecycle.md`
4. The Phase 6 description in the phase sequence mentions "plan artifact freshness check"
5. The Data Flow Diagram's `context-refinement` block has the two appended lines
6. `uv run prek run --files .claude/rules/local-workflow.md` exits 0

## Verification Steps

1. `Grep(pattern="Artifact Type", path=".claude/rules/local-workflow.md",
   output_mode="content")` — confirm column header and four row values
2. `Grep(pattern="Plan Artifact Lifecycle", path=".claude/rules/local-workflow.md",
   output_mode="content")` — confirm section heading
3. `Grep(pattern="plan-artifact-lifecycle.md", path=".claude/rules/local-workflow.md",
   output_mode="content")` — confirm link target present
4. `Grep(pattern="freshness check", path=".claude/rules/local-workflow.md",
   output_mode="content")` — confirm Phase 6 description updated
5. `Grep(pattern="DIVERGENCE_REQUIRING_REVIEW", path=".claude/rules/local-workflow.md",
   output_mode="content")` — confirm data flow diagram updated
6. `uv run prek run --files .claude/rules/local-workflow.md`

## Handoff

Return:

- Line ranges of each change made
- The exact new text of the Phase 6 description
- The exact new text of the `## Plan Artifact Lifecycle` section
- Linter pass/fail

---

## Task T3: Update start-task SKILL.md — Add Divergence Recording Step

```yaml
---
task: T3
title: Update start-task SKILL.md — add divergence recording step 5a
status: complete
started: '2026-03-02T12:00:00Z'
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: [T1]
priority: 2
complexity: low
accuracy-risk: low
parallelize-with: [T2, T5]
reason: T2, T3, T5 write to different files with no overlap
divergence-notes: 1
handoff: >
  Report: exact location of new step 5a in SKILL.md (line numbers),
  linter pass/fail.
---
```

## Context

This task was planned as a standalone update. The `/start-task` skill is loaded by
sub-agents when they execute tasks. Adding divergence recording instructions ensures
agents capture implementation deviations during task execution, before
`/complete-implementation` runs the freshness check.

T1 must complete first because step 5a references the policy document at
`.claude/docs/plan-artifact-lifecycle.md`.

Architecture spec source: [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
section "Modifications to `/start-task` SKILL.md".

## Objective

Insert a new step 5a into `.claude/skills/start-task/SKILL.md` between the existing step 4
(write active-task context file) and step 5 (implement against acceptance criteria),
instructing the agent to record divergence observations during implementation.

## Required Inputs

- [.claude/skills/start-task/SKILL.md](../.claude/skills/start-task/SKILL.md) — file to
  modify; read before editing; note current step numbering
- [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md) —
  section "Modifications to `/start-task` SKILL.md", step 5a content
- `.claude/docs/plan-artifact-lifecycle.md` — must exist (T1 output); used as link target

## Requirements

1. Read `.claude/skills/start-task/SKILL.md` to confirm the exact current wording of step 4
   (write active-task context file) and step 5 (implement against acceptance criteria)
2. Insert a new numbered step between step 4 and step 5. The inserted content must be:

   ```markdown
   5. **Record divergence observations during implementation.**

      While implementing, if you discover that the architect spec or feature-context
      describes something that does not match what you are implementing, append a
      divergence note to the task file under a `## Divergence Notes` section.

      **When to record**: Record a divergence note when ALL of these hold:
      - You are implementing something that differs from what the architect spec or
        feature-context describes
      - The difference is not a trivial implementation detail (e.g., different variable
        name, different import path)
      - The difference affects the observable behavior, structure, or scope of the feature

      **Divergence note format**:

      ```markdown
      ## Divergence Notes

      ### DN-1: {Brief title}

      - **Plan artifact**: plan/architect-{slug}.md, section "{section name}"
      - **Plan claim**: "{quoted text from plan artifact}"
      - **Actual implementation**: "{what was actually done and why}"
      - **Classification**: design-refinement | intent-divergence
      - **Recorded**: {ISO timestamp}
      ```

      After appending a note, update `divergence-notes: {count}` in YAML frontmatter
      (or add `**Divergence Notes**: {count}` in legacy format).

      For full artifact classification rules and divergence thresholds, see
      [.claude/docs/plan-artifact-lifecycle.md](./../docs/plan-artifact-lifecycle.md).
   ```

3. Renumber the original step 5 (implement against acceptance criteria) to step 6
4. Preserve all other existing content unchanged

## Constraints

- Do not modify any step content other than the renumbering of the original step 5
- The new step must be inserted, not replacing any existing step
- Do not change the SKILL.md frontmatter
- Use `./` relative paths in all new markdown links (note: path from SKILL.md to docs is
  `./../docs/plan-artifact-lifecycle.md` — verify this resolves correctly given the file's
  location at `.claude/skills/start-task/SKILL.md`)
- All new code fences must have language specifiers
- Surround all fenced code blocks with blank lines

## Expected Outputs

- File modified: `/home/user/claude_skills/.claude/skills/start-task/SKILL.md`

## Acceptance Criteria

1. A step titled "Record divergence observations during implementation" exists in the file
2. The step contains the divergence note format block with `DN-1`, `Plan artifact`,
   `Plan claim`, `Actual implementation`, `Classification`, `Recorded` fields
3. The step contains the "when to record" criteria (all three conditions)
4. The step contains a link to `.claude/docs/plan-artifact-lifecycle.md`
5. The original "implement against acceptance criteria" step appears after the new step
6. `uv run prek run --files .claude/skills/start-task/SKILL.md` exits 0

## Verification Steps

1. `Grep(pattern="Divergence Notes", path=".claude/skills/start-task/SKILL.md",
   output_mode="content", -C=3)` — confirm the new step is present with context
2. `Grep(pattern="plan-artifact-lifecycle.md",
   path=".claude/skills/start-task/SKILL.md", output_mode="content")` — confirm link
3. `Grep(pattern="Implement against", path=".claude/skills/start-task/SKILL.md",
   output_mode="content")` — confirm original implementation step still present after
   the new step
4. `uv run prek run --files .claude/skills/start-task/SKILL.md`

## Handoff

Return:

- The line numbers of the inserted step 5a
- The exact text of the link to the policy document as it appears in the file
- Linter pass/fail

## Divergence Notes

### DN-1: Corrected relative link path to policy document

- **Plan artifact**: plan/tasks-6-plan-artifact-lifecycle.md, section "Requirements"
- **Plan claim**: "path from SKILL.md to docs is `./../docs/plan-artifact-lifecycle.md`"
- **Actual implementation**: Used `./../../docs/plan-artifact-lifecycle.md` because SKILL.md is at `.claude/skills/start-task/SKILL.md` (3 levels deep from repo root), so `./../docs/` resolves to `.claude/skills/docs/` (wrong). `./../../docs/` resolves to `.claude/docs/` (correct). The constraint text itself said "verify this resolves correctly", confirming the intent was correctness over literal match.
- **Classification**: design-refinement
- **Recorded**: 2026-03-02T12:05:00Z

---

## Task T4: Update complete-implementation SKILL.md — Expand Phase 6 Description

```yaml
---
task: T4
title: Update complete-implementation SKILL.md — expand Phase 6 description
status: complete
started: 2026-03-02T00:00:00Z
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: [T5]
priority: 3
complexity: low
accuracy-risk: low
parallelize-with: []
reason: T4 depends on T5 completing so Phase 6 description accurately reflects the
  extended context-refinement agent behavior
handoff: >
  Report: exact new text of Phase 6 section, location of new post-Phase-6
  section, linter pass/fail.
---
```

## Context

This task was planned as a standalone update. The `/complete-implementation` skill
orchestrates the six quality gate phases. The Phase 6 description currently describes
only the Context Manifest update. It must be expanded to describe the plan artifact
freshness check, and a new section must be added describing how the orchestrator handles
the `DIVERGENCE_REQUIRING_REVIEW` output.

T5 must complete first because the Phase 6 description accurately references the extended
context-refinement agent behavior, which is defined in T5.

Architecture spec source: [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
section "Modified `/complete-implementation` Skill".

## Objective

Update `.claude/skills/complete-implementation/SKILL.md` to expand the Phase 6 description
and add post-Phase-6 orchestrator behavior for surfacing divergence findings to the human.

## Required Inputs

- [.claude/skills/complete-implementation/SKILL.md](../.claude/skills/complete-implementation/SKILL.md)
  — file to modify; read before editing
- [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md) —
  section "Modified `/complete-implementation` Skill", subsections "Phase 6 Update" and
  "Orchestrator Post-Phase-6 Behavior"
- [plugins/python3-development/agents/context-refinement.md](../plugins/python3-development/agents/context-refinement.md)
  — read to confirm the `DIVERGENCE_REQUIRING_REVIEW` output block name matches what T5
  will have added

## Requirements

### Phase 6 description update

1. Find the `## Phase 6: Context Refinement` section in the SKILL.md
2. The current text is:
   `Launch \`context-refinement\` to update the task file Context Manifest with discoveries
   from implementation (only if needed).`
3. Replace with:
   `Launch \`context-refinement\` to update the task file Context Manifest with discoveries
   from implementation AND perform a plan artifact freshness check against the
   feature-context and architect spec. The agent compares key claims in plan artifacts
   against the actual implementation and classifies findings as design-refinement or
   intent-divergence (see [.claude/docs/plan-artifact-lifecycle.md](./../docs/plan-artifact-lifecycle.md)).`

### Post-Phase-6 section addition

4. After the `## Phase 6` section and before `## Recursive Follow-up Handling`, insert a
   new section:

   ```markdown
   ## Post-Phase-6: Surface Divergence Findings

   After Phase 6 completes, check the `context-refinement` agent output for a
   `DIVERGENCE_REQUIRING_REVIEW` block.

   If present, include in the final output to the human:

   ```text
   Plan artifacts have intent divergences requiring your review.
   See: [annotated artifact paths from agent output]
   Divergences:
     [list from DIVERGENCE_REQUIRING_REVIEW block]
   ```

   This is informational, not blocking. The human reviews at their discretion.
   If absent, no additional output is needed — the feature proceeds normally.
   ```

## Constraints

- Read the file before editing to confirm exact current Phase 6 text
- Do not modify Phases 1 through 5
- Do not modify `## Recursive Follow-up Handling`
- The link to `plan-artifact-lifecycle.md` must use relative path appropriate for the
  SKILL.md file location at `.claude/skills/complete-implementation/SKILL.md`
  (path: `./../docs/plan-artifact-lifecycle.md`)
- All new code fences must have language specifiers
- Surround all fenced code blocks with blank lines

## Expected Outputs

- File modified: `/home/user/claude_skills/.claude/skills/complete-implementation/SKILL.md`

## Acceptance Criteria

1. Phase 6 description mentions "plan artifact freshness check"
2. Phase 6 description mentions "design-refinement or intent-divergence"
3. Phase 6 description contains a link to `.claude/docs/plan-artifact-lifecycle.md`
4. A `## Post-Phase-6: Surface Divergence Findings` section exists between Phase 6 and
   Recursive Follow-up Handling
5. The new section contains `DIVERGENCE_REQUIRING_REVIEW` as the signal to check
6. `uv run prek run --files .claude/skills/complete-implementation/SKILL.md` exits 0

## Verification Steps

1. `Grep(pattern="freshness check",
   path=".claude/skills/complete-implementation/SKILL.md", output_mode="content")`
   — confirm Phase 6 updated
2. `Grep(pattern="DIVERGENCE_REQUIRING_REVIEW",
   path=".claude/skills/complete-implementation/SKILL.md", output_mode="content")`
   — confirm post-phase-6 section present
3. `Grep(pattern="plan-artifact-lifecycle.md",
   path=".claude/skills/complete-implementation/SKILL.md", output_mode="content")`
   — confirm link present
4. `uv run prek run --files .claude/skills/complete-implementation/SKILL.md`

## Handoff

Return:

- The exact new text of Phase 6
- The exact new text of the Post-Phase-6 section
- Linter pass/fail

---

## Task T5: Update context-refinement.md — Add Plan Artifact Freshness Check Steps

```yaml
---
task: T5
title: Update context-refinement.md — add plan artifact freshness check steps 5-8
status: complete
started: 2026-03-02T00:00:00Z
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: [T1]
priority: 2
complexity: high
accuracy-risk: medium
parallelize-with: [T2, T3]
reason: T2, T3, T5 write to different files with no overlap
handoff: >
  Report: line numbers of each new section added, confirmation that DIVERGENCE_REQUIRING_REVIEW
  block format matches spec, linter pass/fail.
---
```

## Context

This task was planned as a standalone update. The `context-refinement` agent currently
performs only a task-scoped Context Manifest update. This task expands its scope to cover
plan artifact freshness checking across the feature's feature-context and architect spec
files.

T1 must complete first because the agent prompt references
`.claude/docs/plan-artifact-lifecycle.md` for classification rules.

Architecture spec source: [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
sections "Extended Context-Refinement Agent" and "Modifications to `context-refinement.md`
Agent Prompt".

## Objective

Update `plugins/python3-development/agents/context-refinement.md` to: (1) expand the
YOUR MISSION statement to include plan artifact freshness checking, (2) add Steps 5-8 to
the Process section, (3) add the `DIVERGENCE_REQUIRING_REVIEW` output block to the Output
Format section, and (4) add a reference to the canonical policy document.

## Required Inputs

- [plugins/python3-development/agents/context-refinement.md](../plugins/python3-development/agents/context-refinement.md)
  — file to modify; read the full file before editing
- [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md) —
  sections "Extended Context-Refinement Agent" (steps 5-8),
  "Modifications to context-refinement.md Agent Prompt" (mission update, output format),
  "Divergence Recording" (annotation format)
- `.claude/docs/plan-artifact-lifecycle.md` — must exist (T1 output); used as link target

## Requirements

### YOUR MISSION update

1. Find the `## YOUR MISSION` section. Current text:
   `Check IF context has drifted or new discoveries were made during the implementation
   session. Only update the context manifest if changes are needed.`
2. Replace with:
   `Check IF context has drifted or new discoveries were made during the implementation
   session. Update the context manifest if changes are needed. Then perform a plan artifact
   freshness check: compare the feature-context and architect spec against the actual
   implementation to detect and classify divergences as design-refinement or
   intent-divergence.`

### Add policy reference

3. After the `## Context About Your Invocation` section, insert a new paragraph:
   `For artifact classification rules, divergence thresholds, and annotation formats, see
   [.claude/docs/plan-artifact-lifecycle.md](./../../docs/plan-artifact-lifecycle.md).`
   (Note: path from agent file at
   `plugins/python3-development/agents/context-refinement.md` to
   `.claude/docs/plan-artifact-lifecycle.md` — verify the relative path resolves correctly)

### Add Steps 5-8 to the Process section

4. After the existing Step 4 (Update Format), append four new steps to the `## Process`
   section:

   **Step 5: Locate Plan Artifacts and Intent Source**

   ```markdown
   ### Step 5: Locate Plan Artifacts and Intent Source

   1. Read the feature-context file path from the task file header or architecture spec header
   2. Read the architecture spec file path from the task file header
   3. Read the `Intent Source` path from the feature-context or architecture spec header to
      locate the human-decision artifact
   4. If `Intent Source` is absent (pre-policy artifact), skip intent-divergence
      classification — treat all divergences as design-refinement
   ```

   **Step 6: Collect Divergence Evidence**

   ```markdown
   ### Step 6: Collect Divergence Evidence

   1. Read all task files for the feature (all tasks, not just the current one)
   2. Collect all `## Divergence Notes` sections from task bodies
   3. Collect all `### Discovered During Implementation` sections from Context Manifests
   4. Compare key claims in the architecture spec against the actual implementation files
   ```

   **Step 7: Classify Divergences**

   ```markdown
   ### Step 7: Classify Divergences

   For each divergence found:

   1. If `Intent Source` is available, read the human-decision artifact
   2. Compare the divergence against the human's stated intent (scope, goals, constraints)
   3. Apply the divergence threshold table from the policy document:
      - Implementation detail differs from architect spec → design-refinement (auto-record)
      - Approach differs but achieves same goal → design-refinement (auto-record, annotate
        architect spec)
      - Scope expanded or reduced beyond backlog item → intent-divergence (flag for review)
      - Goal redefined or abandoned → intent-divergence (flag for review)
      - Constraint from grooming output violated → intent-divergence (flag for review)
   ```

   **Step 8: Annotate Plan Artifacts**

   ```markdown
   ### Step 8: Annotate Plan Artifacts

   If divergences were found, append a `## Post-Implementation Annotations` section to
   the feature-context file and architect spec file. Use the annotation format:

   ```markdown
   ## Post-Implementation Annotations

   _Added by context-refinement agent on {date}_

   ### Design Refinements

   1. **{Title}**: {Description of what changed and why}
      - Original: "{quoted from plan}"
      - Actual: "{what was implemented}"
      - Recorded in: {task file path}, DN-{N}

   ### Intent Divergences Requiring Review

   1. **{Title}**: {Description of how implementation diverges from human intent}
      - Human intent: "{quoted from backlog item or grooming output}"
      - Actual: "{what was implemented}"
      - Recorded in: {task file path}, DN-{N}
      - **Action needed**: Human review required
   ```

   If no intent divergences are found, omit the `### Intent Divergences Requiring Review`
   subsection.

   Annotation rule: APPEND only. Never modify the original content of the plan artifact.
   ```

### Update Output Format section

5. In the `## Output Format` section, update the "On Success - Context Updated" block:
   - Change the SUMMARY line template to:
     `SUMMARY: Context manifest updated with [N] discoveries. Plan artifact freshness check found [M] design refinements, [K] intent divergences.`
   - Add `ARTIFACTS` entries for the annotated plan files:
     `- Annotated feature context: [path] (if annotated)`
     `- Annotated architect spec: [path] (if annotated)`

6. Add a new output block after "On Success - Context Updated" for when intent divergence
   is found:

   ```markdown
   ### On Success - Intent Divergence Found

   ```text
   STATUS: DONE
   SUMMARY: Context manifest updated. Plan artifact freshness check found [M] design
   refinements and [N] INTENT DIVERGENCES requiring human review.
   ARTIFACTS:
     - Updated task file: [path]
     - Annotated feature context: [path]
     - Annotated architect spec: [path]
   DIVERGENCE_REQUIRING_REVIEW:
     1. [Title]: [Brief description]
        - Human intent: [quoted]
        - Actual: [description]
        - Task: [task file path]
   RISKS:
     - Intent divergence detected -- human review needed before feature is considered complete
   NOTES:
     - [Summary]
   ```
   ```

## Constraints

- Read the full file before editing — do not skip any section
- All new steps append after Step 4; do not renumber or modify Steps 1-4
- The annotation operation in Step 8 is append-only; the instructions must make this clear
- The relative path from `plugins/python3-development/agents/context-refinement.md` to
  `.claude/docs/plan-artifact-lifecycle.md` must be verified before writing (count
  directory levels up from the agent file's location)
- All new code fences must have language specifiers
- Surround all fenced code blocks with blank lines

## Expected Outputs

- File modified:
  `/home/user/claude_skills/plugins/python3-development/agents/context-refinement.md`

## Acceptance Criteria

1. `## YOUR MISSION` includes "plan artifact freshness check"
2. `## YOUR MISSION` includes "design-refinement or intent-divergence"
3. A policy document reference link exists in the file pointing to
   `.claude/docs/plan-artifact-lifecycle.md`
4. Steps 5, 6, 7, and 8 exist in the `## Process` section
5. Step 8 contains the `## Post-Implementation Annotations` annotation format with both
   `### Design Refinements` and `### Intent Divergences Requiring Review` subsections
6. The Output Format section contains a `DIVERGENCE_REQUIRING_REVIEW` block
7. The SUMMARY template in "On Success - Context Updated" references design refinements
   and intent divergences
8. `uv run prek run --files plugins/python3-development/agents/context-refinement.md`
   exits 0

## Verification Steps

1. `Grep(pattern="freshness check",
   path="plugins/python3-development/agents/context-refinement.md",
   output_mode="content")` — confirm mission statement updated
2. `Grep(pattern="Step 5",
   path="plugins/python3-development/agents/context-refinement.md",
   output_mode="content", -C=2)` — confirm Step 5 present
3. `Grep(pattern="DIVERGENCE_REQUIRING_REVIEW",
   path="plugins/python3-development/agents/context-refinement.md",
   output_mode="content")` — confirm output block present
4. `Grep(pattern="Post-Implementation Annotations",
   path="plugins/python3-development/agents/context-refinement.md",
   output_mode="content")` — confirm annotation format present
5. `Grep(pattern="plan-artifact-lifecycle.md",
   path="plugins/python3-development/agents/context-refinement.md",
   output_mode="content")` — confirm policy reference link present
6. `uv run prek run --files plugins/python3-development/agents/context-refinement.md`

## CoVe Checks

- Key claims to verify:
  - The relative path from `plugins/python3-development/agents/context-refinement.md`
    to `.claude/docs/plan-artifact-lifecycle.md`
  - That adding Steps 5-8 after Step 4 does not create a numbering conflict with any
    subsections or numbered items already in the file

- Verification questions (falsifiable):
  1. Reading `plugins/python3-development/agents/context-refinement.md` — does the file
     currently contain a Step 4 and no Step 5? If Step 5 already exists, the new steps
     must use different labels (e.g., 5a, 5b) or a new subsection.
  2. From `plugins/python3-development/agents/context-refinement.md`, what is the
     correct relative path to `.claude/docs/`? Count: the file is at
     `plugins/python3-development/agents/` — three levels deep from repo root. The target
     is `.claude/docs/` — one level deep from repo root. Correct relative path:
     `./../../.claude/docs/plan-artifact-lifecycle.md`.

- Evidence to collect:
  - Read the file and confirm whether "Step 5" text already appears anywhere
  - Verify path: `Read(file_path=".claude/docs/plan-artifact-lifecycle.md")` — confirm
    it exists at that path after T1 completes
  - Confirm the resolved relative path by counting directory depth

- Revision rule:
  If Step 5 already exists in the file (from a prior modification), rename new steps to
  avoid collision. If the relative path resolution is uncertain, use the absolute path
  approach from the architecture spec as a fallback and note it in the handoff.

## Handoff

Return:

- Line numbers of each new section added
- The exact relative path used for the policy document link and confirmation it resolves
- Confirmation that the `DIVERGENCE_REQUIRING_REVIEW` block format matches the spec
- Whether any CoVe checks required revision and what changed
- Linter pass/fail

---

## Task T6: Update TASK_FILE_FORMAT.md — Add divergence-notes Field

```yaml
---
task: T6
title: Update TASK_FILE_FORMAT.md — add divergence-notes optional field
status: complete
started: 2026-03-02T12:00:00Z
completed: 2026-03-02T00:00:00Z
agent: general-purpose
dependencies: []
priority: 1
complexity: low
accuracy-risk: low
parallelize-with: [T1]
reason: T6 and T1 write to different files with no overlap
handoff: >
  Report: line numbers of each addition in TASK_FILE_FORMAT.md, confirmation that
  divergence-notes appears in both the Optional Fields table and JSON schema,
  backward-compatibility validation result.
---
```

## Context

This task was planned as a standalone update. `TASK_FILE_FORMAT.md` is the schema
document that defines valid YAML frontmatter fields for task files. The `divergence-notes`
field needs to be added as an optional field so it is recognized as part of the schema,
enabling the `context-refinement` agent to quickly identify tasks that recorded divergences.

T6 has no dependencies — the schema change is self-contained and does not reference the
policy document.

Architecture spec source: [plan/architect-plan-artifact-lifecycle.md](./architect-plan-artifact-lifecycle.md),
section "Task File Format Extension".

## Objective

Add `divergence-notes` as an optional integer field to the Optional Fields table and the
JSON Schema `properties` block in `.claude/docs/TASK_FILE_FORMAT.md`.

## Required Inputs

- [.claude/docs/TASK_FILE_FORMAT.md](../.claude/docs/TASK_FILE_FORMAT.md) — file to modify;
  read before editing; note current Optional Fields table structure and JSON schema
  properties block

## Requirements

### Optional Fields table addition

1. Read the Optional Fields table (section "Optional Fields" under "Field Definitions")
2. Add a new row for `divergence-notes` after the existing `analysis-method` row:

   | Field | Type | Description | Example |
   | `divergence-notes` | integer | Count of divergence notes recorded during implementation | `2` |

3. The row must follow the same column order and formatting as existing rows

### JSON Schema addition

4. Find the JSON schema `properties` block (inside the `## YAML Schema` section)
5. After the `"analysis-method"` property definition and before the closing `}` of the
   `"properties"` object, add:

   ```json
   "divergence-notes": {
     "type": "integer",
     "minimum": 0,
     "default": 0,
     "description": "Count of divergence notes recorded during implementation"
   }
   ```

6. Ensure the JSON remains valid (trailing comma on the preceding property if needed, or
   no trailing comma on the new property if it is last)

### Template update

7. Find the template file contents block in `## Template File` section
8. Add a commented-out optional field line for `divergence-notes` after
   `# analysis-method`:
   ```text
   # divergence-notes: 0   # OPTIONAL: integer count of ## Divergence Notes sections in body
   ```

## Constraints

- Read the file fully before editing to understand current structure
- Do not modify any existing field definitions
- The JSON schema addition must maintain valid JSON syntax — verify by reading surrounding
  context carefully before writing
- Do not add `divergence-notes` to the Required Fields table
- Do not change the `## Migration Guide` section

## Expected Outputs

- File modified: `/home/user/claude_skills/.claude/docs/TASK_FILE_FORMAT.md`

## Acceptance Criteria

1. `divergence-notes` appears in the Optional Fields table with type `integer`,
   description including "divergence notes", and example `2`
2. `divergence-notes` appears in the JSON schema `properties` block with `"type":
   "integer"`, `"minimum": 0`, `"default": 0`
3. The template block contains a commented `divergence-notes` line
4. Existing backward-compatibility claim holds: running
   `uv run plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py
   validate . plugin-linter` succeeds (existing task files without `divergence-notes`
   still validate — the field is optional with default 0)
5. `uv run prek run --files .claude/docs/TASK_FILE_FORMAT.md` exits 0

## Verification Steps

1. `Grep(pattern="divergence-notes", path=".claude/docs/TASK_FILE_FORMAT.md",
   output_mode="content", -C=2)` — confirm field appears in table, schema, and template
2. `Grep(pattern="\"minimum\": 0", path=".claude/docs/TASK_FILE_FORMAT.md",
   output_mode="content")` — confirm JSON schema minimum constraint
3. Run backward-compatibility check:
   `uv run plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py
   validate . plugin-linter`
   — expect exit 0 with no schema errors
4. `uv run prek run --files .claude/docs/TASK_FILE_FORMAT.md`

## Handoff

Return:

- The exact text of the new Optional Fields table row
- The exact JSON added to the schema properties block
- Output of the backward-compatibility validation command
- Linter pass/fail

---

## SYNC CHECKPOINT 1: All Tasks Complete

Convergence point: T1 + T2 + T3 + T4 + T5 + T6 outputs

### Quality Gates

1. All six tasks have `status: complete` in this file
2. `.claude/docs/plan-artifact-lifecycle.md` exists with all nine required sections
3. `Grep(pattern="freshness check", path=".claude/skills/complete-implementation/SKILL.md")`
   returns a match
4. `Grep(pattern="DIVERGENCE_REQUIRING_REVIEW",
   path="plugins/python3-development/agents/context-refinement.md")` returns a match
5. `Grep(pattern="divergence-notes", path=".claude/docs/TASK_FILE_FORMAT.md")` returns
   matches in table, schema, and template
6. All linter runs passed (T1 through T6 each ran
   `uv run prek run --files <modified-file>` with exit 0)
7. Backward-compatibility check passed:
   `uv run plugins/python3-development/skills/implementation-manager/scripts/implementation_manager.py
   validate . plugin-linter` exits 0

### Cross-Reference Integrity Check

Verify all new inter-file references resolve:

1. `Grep(pattern="plan-artifact-lifecycle.md", path=".claude/rules/local-workflow.md")`
   — T2 must reference T1's output
2. `Grep(pattern="plan-artifact-lifecycle.md",
   path=".claude/skills/start-task/SKILL.md")` — T3 must reference T1's output
3. `Grep(pattern="plan-artifact-lifecycle.md",
   path=".claude/skills/complete-implementation/SKILL.md")` — T4 must reference T1's output
4. `Grep(pattern="plan-artifact-lifecycle.md",
   path="plugins/python3-development/agents/context-refinement.md")` — T5 must reference
   T1's output

### Reflection Questions

- Do the new divergence note format and the annotation format in context-refinement.md
  use consistent field names?
- Does the DIVERGENCE_REQUIRING_REVIEW block format in context-refinement.md match the
  format described in complete-implementation SKILL.md?
- Are there any paths in the new content that cross plugin boundaries in a way that could
  break when the skill is installed in a different location?

Proceed to consider implementation complete after all quality gates pass.
