"""Property-based tests for ComplexityValidator token counting.

Tests:
- Token counting determinism using hypothesis property-based testing
- Threshold boundary conditions using TOKEN_WARNING_THRESHOLD and TOKEN_ERROR_THRESHOLD
- Encoding consistency (cl100k_base)
- Frontmatter exclusion from token counts
- Known sample texts with verified token counts

How:
- Uses hypothesis to generate random text and verify determinism
- Uses exact token counts at threshold boundaries
- Tests frontmatter split logic with various formats
- Validates encoding parameter handling

Why:
- Token counting is critical for complexity measurement
- Must be deterministic for consistent validation
- Thresholds must trigger warnings/errors at exact boundaries
- Ensures ComplexityValidator accuracy and reliability
"""

from __future__ import annotations

import sys
from pathlib import Path

from hypothesis import given, settings, strategies as st

# Add parent directory to path to import plugin_validator
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from plugin_validator import TOKEN_ERROR_THRESHOLD, TOKEN_WARNING_THRESHOLD, ComplexityValidator


def generate_exact_token_content(target_tokens: int) -> str:
    """Generate text content with exactly target_tokens tokens.

    Args:
        target_tokens: Target number of tokens using cl100k_base encoding

    Returns:
        Text content with exactly target_tokens tokens

    Note:
        Uses iterative approach to hit exact token count
    """
    import tiktoken

    enc = tiktoken.get_encoding("cl100k_base")

    # Build up content word by word
    words = []
    for i in range(target_tokens * 2):  # Overestimate to reach target
        words.append(f"word{i}")
        content = " ".join(words)
        token_count = len(enc.encode(content))

        if token_count == target_tokens:
            return content
        if token_count > target_tokens:
            # Went over - try removing last word
            words.pop()
            content = " ".join(words)
            token_count = len(enc.encode(content))

            # If still over or exact match, return
            if token_count <= target_tokens:
                # Add single characters until we hit exact count
                while token_count < target_tokens:
                    content += "x"
                    token_count = len(enc.encode(content))
                    if token_count == target_tokens:
                        return content
                    if token_count > target_tokens:
                        # Remove the x we just added
                        return content[:-1]
                return content

    # If we get here, return what we have
    return " ".join(words)


class TestTokenCountDeterminism:
    """Property-based tests for token counting determinism.

    Tests: Token counting produces same result for same input
    How: Use hypothesis to generate random text, count tokens multiple times
    Why: Ensures reliability and consistency of complexity measurement
    """

    @given(st.text(min_size=10, max_size=1000))
    @settings(deadline=None)
    def test_same_text_produces_same_count_always(self, text: str) -> None:
        """Test same text always produces same token count.

        Tests: Token counting determinism
        How: Generate random text, count tokens 5 times, verify all counts match
        Why: Critical for consistent validation across multiple runs

        Args:
            text: Random text generated by hypothesis
        """
        validator = ComplexityValidator()

        # Create temporary files with same content
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            skill_path = Path(tmpdir) / "SKILL.md"

            # Create skill with generated text in body
            skill_content = f"""---
description: Test skill for determinism
---

{text}
"""
            skill_path.write_text(skill_content, encoding="utf-8")

            # Run validation multiple times
            results = [validator.validate(skill_path) for _ in range(5)]

            # All results should be identical
            # Check passed status is same
            passed_values = [r.passed for r in results]
            assert all(p == passed_values[0] for p in passed_values), (
                "Token counting produced different passed/failed results for same input"
            )

            # Check error count is same
            error_counts = [len(r.errors) for r in results]
            assert all(c == error_counts[0] for c in error_counts), (
                "Token counting produced different error counts for same input"
            )

            # Check warning count is same
            warning_counts = [len(r.warnings) for r in results]
            assert all(c == warning_counts[0] for c in warning_counts), (
                "Token counting produced different warning counts for same input"
            )

    @given(st.text(min_size=50, max_size=500), st.text(min_size=10, max_size=100))
    @settings(deadline=None)
    def test_frontmatter_changes_dont_affect_body_token_count(self, body: str, frontmatter_desc: str) -> None:
        """Test frontmatter changes don't affect body token count.

        Tests: Frontmatter exclusion from token counting
        How: Same body with different frontmatter should produce same complexity
        Why: Only body content should affect complexity measurement

        Args:
            body: Random body text
            frontmatter_desc: Random frontmatter description
        """
        validator = ComplexityValidator()

        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            # Create two skills with same body but different frontmatter
            skill1_path = Path(tmpdir) / "skill1" / "SKILL.md"
            skill1_path.parent.mkdir()
            skill1_path.write_text(
                f"""---
description: "Short description"
---

{body}
""",
                encoding="utf-8",
            )

            skill2_path = Path(tmpdir) / "skill2" / "SKILL.md"
            skill2_path.parent.mkdir()
            # Much longer frontmatter description
            long_desc = frontmatter_desc * 10
            skill2_path.write_text(
                f"""---
description: "{long_desc}"
tools: Read, Write, Grep, Edit, Bash
model: sonnet
hooks: session-start
---

{body}
""",
                encoding="utf-8",
            )

            # Validate both
            result1 = validator.validate(skill1_path)
            result2 = validator.validate(skill2_path)

            # Both should have same validation result (warnings/errors based on body only)
            assert result1.passed == result2.passed, "Frontmatter differences affected validation result"
            assert len(result1.errors) == len(result2.errors), "Frontmatter differences affected error count"
            assert len(result1.warnings) == len(result2.warnings), "Frontmatter differences affected warning count"


class TestThresholdBoundaries:
    """Test exact threshold boundary conditions.

    Tests: Thresholds trigger warnings/errors at exact token counts
    How: Create content with precise token counts at boundaries
    Why: Users need predictable behavior at documented thresholds
    """

    def test_warning_threshold_below_4000_tokens(self, tmp_path: Path) -> None:
        """Test no warning below TOKEN_WARNING_THRESHOLD.

        Tests: Warning threshold boundary
        How: Create skill with body tokens safely below TOKEN_WARNING_THRESHOLD, validate
        Why: Ensure SK006 warning appears only at >TOKEN_WARNING_THRESHOLD
        """
        validator = ComplexityValidator()

        # Generate content safely below warning threshold
        content = generate_exact_token_content(TOKEN_WARNING_THRESHOLD - 500)

        # Create skill file
        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill below warning threshold
---

{content}
""")

        # Validate
        result = validator.validate(skill_md)

        # Should pass with no warnings (well below threshold)
        assert result.passed is True, "Should pass below threshold"
        assert not any(issue.code == "SK006" for issue in result.warnings), (
            "Should not have warning below TOKEN_WARNING_THRESHOLD"
        )
        assert not any(issue.code == "SK007" for issue in result.errors), (
            "Should not have error below TOKEN_WARNING_THRESHOLD"
        )

    def test_warning_threshold_above_4000_tokens_triggers(self, tmp_path: Path) -> None:
        """Test warning triggers above TOKEN_WARNING_THRESHOLD.

        Tests: Warning threshold boundary (over threshold)
        How: Create skill with body tokens safely above TOKEN_WARNING_THRESHOLD, validate
        Why: Ensure SK006 warning appears when >TOKEN_WARNING_THRESHOLD
        """
        validator = ComplexityValidator()

        # Generate content safely over warning threshold
        content = generate_exact_token_content(TOKEN_WARNING_THRESHOLD + 100)

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill over warning threshold
---

{content}
""")

        result = validator.validate(skill_md)

        # Should have warning SK006
        assert result.passed is True, "Should pass (warnings don't fail)"
        assert any(issue.code == "SK006" for issue in result.warnings), (
            "Should have SK006 warning above TOKEN_WARNING_THRESHOLD"
        )
        assert not any(issue.code == "SK007" for issue in result.errors), (
            "Should not have error below TOKEN_ERROR_THRESHOLD"
        )

    def test_error_threshold_below_6400_tokens(self, tmp_path: Path) -> None:
        """Test no error below TOKEN_ERROR_THRESHOLD.

        Tests: Error threshold boundary
        How: Create skill with body tokens safely below TOKEN_ERROR_THRESHOLD, validate
        Why: Ensure SK007 error appears only at >TOKEN_ERROR_THRESHOLD
        """
        validator = ComplexityValidator()

        # Generate content safely below error threshold (but above warning threshold)
        content = generate_exact_token_content(TOKEN_ERROR_THRESHOLD - 2600)

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill below error threshold
---

{content}
""")

        result = validator.validate(skill_md)

        # Should have warning but NOT error
        assert result.passed is True, "Should pass below error threshold"
        assert any(issue.code == "SK006" for issue in result.warnings), (
            "Should have warning (>TOKEN_WARNING_THRESHOLD tokens)"
        )
        assert not any(issue.code == "SK007" for issue in result.errors), (
            "Should not have error below TOKEN_ERROR_THRESHOLD"
        )

    def test_error_threshold_above_6400_tokens_triggers(self, tmp_path: Path) -> None:
        """Test error triggers above TOKEN_ERROR_THRESHOLD.

        Tests: Error threshold boundary (over threshold)
        How: Create skill with body tokens safely above TOKEN_ERROR_THRESHOLD, validate
        Why: Ensure SK007 error appears when >TOKEN_ERROR_THRESHOLD
        """
        validator = ComplexityValidator()

        # Generate content safely over error threshold
        content = generate_exact_token_content(TOKEN_ERROR_THRESHOLD + 200)

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill over error threshold
---

{content}
""")

        result = validator.validate(skill_md)

        # Should have error SK007
        assert result.passed is False, "Should fail above TOKEN_ERROR_THRESHOLD"
        assert any(issue.code == "SK007" for issue in result.errors), (
            "Should have SK007 error above TOKEN_ERROR_THRESHOLD"
        )

    def test_no_warning_well_below_threshold(self, tmp_path: Path) -> None:
        """Test no warning well below TOKEN_WARNING_THRESHOLD.

        Tests: Well below warning threshold
        How: Create skill with body tokens well below TOKEN_WARNING_THRESHOLD, validate
        Why: Ensure no warnings well below TOKEN_WARNING_THRESHOLD
        """
        validator = ComplexityValidator()

        # Generate content well below all thresholds
        content = generate_exact_token_content(TOKEN_WARNING_THRESHOLD - 1400)

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill well below thresholds
---

{content}
""")

        result = validator.validate(skill_md)

        # Should pass with no warnings or errors
        assert result.passed is True, "Should pass well below thresholds"
        assert len(result.warnings) == 0, "Should have no warnings below TOKEN_WARNING_THRESHOLD"
        assert len(result.errors) == 0, "Should have no errors below TOKEN_WARNING_THRESHOLD"


class TestEncodingConsistency:
    """Test encoding consistency (cl100k_base).

    Tests: Validator uses correct encoding for Claude
    How: Verify token counts match cl100k_base encoding
    Why: Ensures compatibility with Claude's token counting
    """

    def test_encoding_matches_cl100k_base(self, tmp_path: Path) -> None:
        """Test ComplexityValidator uses cl100k_base encoding.

        Tests: Encoding parameter handling
        How: Create known text, verify token count matches cl100k_base
        Why: Ensure Claude-compatible token measurement
        """
        validator = ComplexityValidator()

        import tiktoken

        enc = tiktoken.get_encoding("cl100k_base")

        # Known test text
        test_text = "Hello world! This is a test of token counting with various symbols: @#$%^&*()"
        len(enc.encode(test_text))

        # Create skill file
        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test encoding consistency
---

{test_text}
""")

        # Validate
        result = validator.validate(skill_md)

        # The validator should use cl100k_base internally
        # We can't directly check the count, but we can verify behavior is consistent
        # by checking the result matches expected threshold behavior

        # With our short text, should definitely pass
        assert result.passed is True, "Short text should pass"
        assert len(result.warnings) == 0, "Short text should have no warnings"
        assert len(result.errors) == 0, "Short text should have no errors"

    def test_unicode_handling(self, tmp_path: Path) -> None:
        """Test token counting handles Unicode correctly.

        Tests: Unicode character encoding
        How: Create text with Unicode characters, validate token counting works
        Why: Ensures international character support
        """
        validator = ComplexityValidator()

        # Text with various Unicode characters
        unicode_text = """
        Hello 世界! Здравствуй мир! مرحبا بالعالم!
        Emoji test: 🚀 🎉 💻 🔬
        Math: ∑∫∂∇ ∀∃∈∉
        """

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(
            f"""---
description: Test Unicode handling
---

{unicode_text}
""",
            encoding="utf-8",
        )

        # Should handle Unicode without errors
        result = validator.validate(skill_md)

        # Should complete validation without crash
        assert isinstance(result.passed, bool), "Should return valid result"
        # Short unicode text should pass
        assert result.passed is True, "Short Unicode text should pass"


class TestFrontmatterExclusion:
    """Test frontmatter is excluded from token count.

    Tests: Only body content is measured
    How: Vary frontmatter size while keeping body constant
    Why: Frontmatter should not affect complexity measurement
    """

    def test_large_frontmatter_small_body_passes(self, tmp_path: Path) -> None:
        """Test large frontmatter doesn't trigger warnings.

        Tests: Frontmatter exclusion from count
        How: Create skill with large frontmatter but small body
        Why: Ensure frontmatter is correctly excluded from complexity
        """
        validator = ComplexityValidator()

        # Generate large frontmatter description using helper
        large_desc = generate_exact_token_content(5000)  # 5000 tokens in description

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: "{large_desc}"
tools: Read, Write, Grep, Edit, Bash, Task, WebSearch, WebFetch
model: sonnet
hooks: session-start, session-end
skills: skill-one, skill-two, skill-three
---

# Small Body

This is a very small body section with minimal content.
Just a few sentences to verify frontmatter exclusion works correctly.
""")

        result = validator.validate(skill_md)

        # Should pass because body is small (frontmatter excluded)
        assert result.passed is True, "Should pass with small body despite large frontmatter"
        assert len(result.warnings) == 0, "Should have no warnings (body is small)"
        assert len(result.errors) == 0, "Should have no errors (body is small)"

    def test_small_frontmatter_large_body_triggers_warning(self, tmp_path: Path) -> None:
        """Test small frontmatter with large body triggers warning.

        Tests: Body token counting is accurate
        How: Create skill with minimal frontmatter but large body (>TOKEN_WARNING_THRESHOLD)
        Why: Verify body content is correctly measured
        """
        validator = ComplexityValidator()

        import tiktoken

        enc = tiktoken.get_encoding("cl100k_base")

        # Generate large body content (>TOKEN_WARNING_THRESHOLD tokens)
        large_body = "This is a test sentence for the body. " * 400  # ~8 tokens * 400 = 3200 tokens
        # Add more to reach >TOKEN_WARNING_THRESHOLD
        large_body += "Additional content to reach threshold. " * 150  # ~6 tokens * 150 = 900 more

        tokens_in_body = len(enc.encode(large_body))
        assert tokens_in_body > TOKEN_WARNING_THRESHOLD, (
            f"Test setup: body should be >{TOKEN_WARNING_THRESHOLD} tokens, got {tokens_in_body}"
        )

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: "Short"
---

{large_body}
""")

        result = validator.validate(skill_md)

        # Should have warning because body is large
        assert result.passed is True, "Should pass (warnings don't fail)"
        assert any(issue.code == "SK006" for issue in result.warnings), "Should have warning SK006 for large body"


class TestKnownSampleVerification:
    """Test with known sample texts and verified token counts.

    Tests: Token counting accuracy against known values
    How: Use specific text samples with manually verified token counts
    Why: Provides regression testing against known-good values
    """

    def test_empty_body_has_zero_tokens(self, tmp_path: Path) -> None:
        """Test empty body content has zero tokens.

        Tests: Edge case - empty body
        How: Create skill with frontmatter only, no body
        Why: Verify zero tokens are counted correctly
        """
        validator = ComplexityValidator()

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text("""---
description: Skill with no body content
---
""")

        result = validator.validate(skill_md)

        # Empty body should pass (0 tokens)
        assert result.passed is True, "Empty body should pass"
        assert len(result.warnings) == 0, "Empty body should have no warnings"
        assert len(result.errors) == 0, "Empty body should have no errors"

    def test_known_text_sample(self, tmp_path: Path) -> None:
        """Test known text sample with verified token count.

        Tests: Token counting accuracy
        How: Use specific known text, verify expected token count behavior
        Why: Regression test against manually verified count
        """
        validator = ComplexityValidator()

        import tiktoken

        enc = tiktoken.get_encoding("cl100k_base")

        # Known sample text (from Claude Code documentation example)
        sample_text = """# Example Skill

This is an example skill that demonstrates Claude Code capabilities.

## Purpose

This skill helps users understand how to create effective skills.

## Usage

Activate this skill when you need guidance on skill creation.
"""

        # Verify known token count
        expected_tokens = len(enc.encode(sample_text))
        # This sample should be well under TOKEN_WARNING_THRESHOLD
        assert expected_tokens < 100, f"Test assumption: sample should be <100 tokens, got {expected_tokens}"

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text(f"""---
description: Test skill with known sample
---

{sample_text}
""")

        result = validator.validate(skill_md)

        # Should pass (well under threshold)
        assert result.passed is True, "Known small sample should pass"
        assert len(result.warnings) == 0, "Known small sample should have no warnings"
        assert len(result.errors) == 0, "Known small sample should have no errors"


class TestErrorHandling:
    """Test error handling in token counting.

    Tests: Graceful handling of edge cases
    How: Test various error conditions
    Why: Ensure validator doesn't crash on invalid input
    """

    def test_missing_file_returns_error(self) -> None:
        """Test validation of non-existent file returns error.

        Tests: File reading error handling
        How: Validate path to non-existent file
        Why: Ensure graceful error handling
        """
        validator = ComplexityValidator()

        non_existent = Path("/tmp/definitely-does-not-exist-12345/SKILL.md")
        result = validator.validate(non_existent)

        # Should return error result
        assert result.passed is False, "Should fail for non-existent file"
        assert len(result.errors) > 0, "Should have error for non-existent file"

    def test_malformed_frontmatter_handled_gracefully(self, tmp_path: Path) -> None:
        """Test malformed frontmatter doesn't crash validator.

        Tests: Frontmatter parsing error handling
        How: Create file with unclosed frontmatter, validate
        Why: Ensure validator handles malformed input gracefully
        """
        validator = ComplexityValidator()

        skill_md = tmp_path / "SKILL.md"
        skill_md.write_text("""---
description: Unclosed frontmatter
# Missing closing delimiter

Body content here
""")

        # Should not crash
        result = validator.validate(skill_md)

        # Should return some result (may pass or fail depending on implementation)
        assert isinstance(result.passed, bool), "Should return valid result"
